
version: "3.0"

services:
  backend:
    build: ./backend
    volumes:
      - "./backend/history.log:/backend/history.log"
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend